### PR TITLE
October 2022 news

### PR DESCRIPTION
**Pull request by john-sandall**

### CODE REVIEW

**Review by kynan — CHANGES_REQUESTED** [review]
@john-sandall please remove the PyData London News May 2022 notebook and assets in the `images` folder. I assume this was added by accident?

**Comment by john-sandall** [comment]
Came through from https://github.com/PyDataLondon/News/tree/master/2022-05-31_PyData-News-May-2022/images/PyData%20London%20News%20-%20May%202022%20slides_files I wasn't sure if this stuff is important or why @EmlynC uploaded it all

**Review by kynan — CHANGES_REQUESTED** [review]
Thanks! There's 2 images which aren't referenced and I think can be removed:
* 2022-10-03_PyData-News-October-2022/images/global-diversity-cfp.png
* 2022-10-03_PyData-News-October-2022/images/pycon-italy.png

**Comment by john-sandall** [comment]
Done!

**Review by kynan — APPROVED** [review]
Thanks!

**Pull request merged**
